#!/bin/sh

./manage.py dumpdata --indent=1 \
  exmo2010.monitoring \
  exmo2010.parametertype \
  exmo2010.category \
  exmo2010.subcategory \
  exmo2010.organizationtype \
  exmo2010.parameter \
  exmo2010.parametermonitoringproperties \
  exmo2010.organization \
  exmo2010.federal \
  exmo2010.entity \
> exmo2010/fixtures/initial_data.json
